# Generated by Django 5.2.12 on 2026-03-18 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('asset_type', models.CharField(choices=[('crypto', 'crypto'), ('stock', 'stock')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArbitrageOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheapest_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('highest_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('spread_absolute', models.DecimalField(decimal_places=8, max_digits=20)),
                ('spread_percent', models.DecimalField(decimal_places=4, max_digits=10)),
                ('observed_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='market.asset')),
                ('cheapest_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheap_opportunities', to='market.exchange')),
                ('most_expensive_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expensive_opportunities', to='market.exchange')),
            ],
            options={
                'ordering': ['-spread_percent', '-observed_at'],
                'indexes': [models.Index(fields=['asset', 'observed_at'], name='market_arbi_asset_i_baa281_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='market.asset')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='market.exchange')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['asset', 'recorded_at'], name='market_pric_asset_i_2e22f3_idx'), models.Index(fields=['exchange', 'recorded_at'], name='market_pric_exchang_d1d8d2_idx')],
            },
        ),
    ]
